FROM python:3.12.2

COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && \
    apt-get install -y cron


WORKDIR /app

COPY crontab.txt /app/crontab.txt
RUN crontab /app/crontab.txt

CMD ["cron", "-f"]

