FROM python:3.12.2

WORKDIR /app
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app.py /app/app.py
COPY ./templates /app/templates
COPY ./models /app/models

CMD ["python", "app.py"]