FROM python:3.12.2

WORKDIR /app
COPY /webserver/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app/src

ENV PATH="/app:$PATH"
ENV PYTHONPATH "/app/src"
RUN pip install -e /app/src/web_utils

CMD ["python", "app.py"]